import type { Metadata, Viewport } from "next";
import "./globals.css";
import { SessionProvider } from "@/components/session-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{
        fontFamily: "var(--font-geist-sans, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif)",
      }}>
        <SessionProvider>
          {children}
        </SessionProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
